name: SkyBlock
version: '1.0-SNAPSHOT'
main: de.jan.skyblock.SkyBlock
api-version: '1.21'
author: Jan2808
description: SkyBlock plugin

commands:
  island:
    permission: xxx.xxx
    description: manage all island related commands
    usage: /island <subCommand>
  world:
    permission: xxx.xxx
    description: teleport player to world